---
# If you need to deploy on another group of hosts change the value below 
# to point to another group as defined in your `hosts` file.
# AWS WaDE
- hosts: aws_wade
  vars_files:
    - vars.yml
  gather_facts: yes
  become: yes

  tasks:
  - name: Install system packages
    apt: pkg={{item}} update-cache=yes
    with_items:
      - docker.io
      - git
      - python-pip
      - python-dev

  - name: Install python packages
    pip:
      name: "{{item}}"
      state: latest
    with_items:
      - docker-compose

  - name: Creates clone location and subdirectories
    file: path={{item}} state=directory
    with_items:
      - "{{clone_location}}/conf.d/"

  - name: clone/pull project repo
    git: repo={{shiny_repo}} dest={{clone_location}}/{{app_name}}/src accept_hostkey=True force=True

  - name: copy dockerfile
    template: src=files/dockerfile_shiny.j2 dest={{clone_location}}/{{app_name}}/Dockerfile force=yes

  - name: copy nginx virtualhost
    template: src=files/shiny_server.j2 dest={{clone_location}}/conf.d/{{app_name}}.conf force=yes

  - name: Create wamdam network
    docker_network:
      name: wamdam_wamdam

  - name: Create nginx container if not present
    docker_container:
      name: nginx
      state: started
      image: nginx:latest
      ports:
       - "80:80"
      volumes:
       - "{{clone_location}}/conf.d:/etc/nginx/conf.d"
      networks:
       - name: wamdam_wamdam
         
  - docker_service:
        project_name: "{{app_name}}"
        build: yes
        definition:
          version: '2'
          services:
  
            shiny:
              networks:
              - wamdam_wamdam
              container_name: "{{shiny_container}}"
              restart: always
              build: "{{clone_location}}/{{app_name}}"
              command: bash -c "/usr/bin/shiny-server.sh"
              volumes:
                - "{{clone_location}}/{{app_name}}/src/:/srv/shiny-server/"
              expose:
                - "3838"

          networks:
            wamdam_wamdam:
              external:
                name: wamdam_wamdam

  - name: Restart a container
    docker_container:
      name: nginx
      image: nginx:latest
      state: started
      restart: yes
